### ISSUE TITLE
当内容加圆角，且按下的时候会有奇怪的黑色的边

### ISSUE THREAD

**Issue by kevinroy-lo** [FantasticPornTaiQiang/PTQFlipper#1]
![Screenshot_20230713_184801](https://github.com/FantasticPornTaiQiang/PTQFlipper/assets/12679333/e110a3d9-0cc0-4f5c-be85-bd889ece87db)

**Comment by FantasticPornTaiQiang** [comment]
给一下最小可复现代码，我看看

**Comment by kevinroy-lo** [comment]
`Box(modifier = Modifier.padding(top = 10.dp, end = 20.dp).fillMaxSize()) {
                        val state by rememberPTQBookPageViewState(pageCount = 100)
                        val config by rememberPTQBookPageViewConfig(pageColor = Color.White)
                        PTQBookPageView(
                            state = state, config = config, modifier = Modifier.fillMaxSize().background(
                                Color.Transparent, shape = RoundedCornerShape(
                                    topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
                                )
                            )
                        ) {
                            contents { currentPage, refresh ->
                                Box {
                                    Card(
                                        shape = RoundedCornerShape(
                                            topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
                                        ), colors = CardDefaults.cardColors(
                                            containerColor = Color.White
                                        ), modifier = Modifier.fillMaxSize()
                                    ) {
                                        Text("$currentPage", style = MaterialTheme.typography.bodyLarge)
                                    }
                                }
                                refresh()
                            }
                        }
                    }`

**Comment by kevinroy-lo** [comment]
```kotlin
Box(modifier = Modifier.padding(top = 10.dp, end = 20.dp).fillMaxSize()) {
                        val state by rememberPTQBookPageViewState(pageCount = 100)
                        val config by rememberPTQBookPageViewConfig(pageColor = Color.White)
                        PTQBookPageView(
                            state = state, config = config, modifier = Modifier.fillMaxSize().background(
                                Color.Transparent, shape = RoundedCornerShape(
                                    topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
                                )
                            )
                        ) {
                            contents { currentPage, refresh ->
                                Box {
                                    Card(
                                        shape = RoundedCornerShape(
                                            topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
                                        ), colors = CardDefaults.cardColors(
                                            containerColor = Color.White
                                        ), modifier = Modifier.fillMaxSize()
                                    ) {
                                        Text("$currentPage", style = MaterialTheme.typography.bodyLarge)
                                    }
                                    Image(painter = Images.HomeLeft.painter(), contentDescription = null)
                                }
                                refresh()
                            }
                        }
                    }
```

**Comment by kevinroy-lo** [comment]
就是在PTQBookPageView的modifer中和的Card 里面加载了shape，去做一个圆角的效果，就会出现 这个。

**Comment by FantasticPornTaiQiang** [comment]
看了一下，现在的实现方式暂时不支持设置圆角，我得想想圆角怎么实现

**Comment by FantasticPornTaiQiang** [comment]
书页必须是矩形，因为裁了边（比如圆角）的话，阴影以及翻起来的那一页都不好画，并且书页底色本身只能是非透明的

**Comment by FantasticPornTaiQiang** [comment]
> ```kotlin
> Box(modifier = Modifier.padding(top = 10.dp, end = 20.dp).fillMaxSize()) {
>                         val state by rememberPTQBookPageViewState(pageCount = 100)
>                         val config by rememberPTQBookPageViewConfig(pageColor = Color.White)
>                         PTQBookPageView(
>                             state = state, config = config, modifier = Modifier.fillMaxSize().background(
>                                 Color.Transparent, shape = RoundedCornerShape(
>                                     topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
>                                 )
>                             )
>                         ) {
>                             contents { currentPage, refresh ->
>                                 Box {
>                                     Card(
>                                         shape = RoundedCornerShape(
>                                             topStart = 0.dp, topEnd = 32.dp, bottomEnd = 32.dp, bottomStart = 0.dp
>                                         ), colors = CardDefaults.cardColors(
>                                             containerColor = Color.White
>                                         ), modifier = Modifier.fillMaxSize()
>                                     ) {
>                                         Text("$currentPage", style = MaterialTheme.typography.bodyLarge)
>                                     }
>                                     Image(painter = Images.HomeLeft.painter(), contentDescription = null)
>                                 }
>                                 refresh()
>                             }
>                         }
>                     }
> ```

如果是外面的圆角，在最外面直接Clip就行了，比如你的PTQBookPageView那一级的Modifier。但是这两天想了下，如果翻起来的那一页要画圆角，不知道怎么画，因为有个问题就是，当你翻的很小的时候，就是只翻开了一点的时候，你设的圆角的半径会超过翻开了的边长度，不知道怎么处理了。
