### ISSUE TITLE
感觉卷曲效果前面的文字会有一点被往前推的感觉, 不是很自然.

### ISSUE THREAD

**Issue by Liloupar** [FantasticPornTaiQiang/PTQFlipper#2]
和多看/微信读书的比起来.
这个还有办法优化吗? 求问大佬

**Comment by FantasticPornTaiQiang** [comment]
不好意思，没有看到github的issue，现在才看到。

不知道你说的优化是指什么？是指当前页背页的镜像的半透明效果吗？

**Comment by Liloupar** [comment]
> 不好意思，没有看到github的issue，现在才看到。
> 
> 不知道你说的优化是指什么？是指当前页背页的镜像的半透明效果吗？

晚上回去我补充个截图和标注, 文字不太好说明 :P @FantasticPornTaiQiang

**Comment by FantasticPornTaiQiang** [comment]
好的

**Comment by Liloupar** [comment]
> 

![image](https://github.com/FantasticPornTaiQiang/PTQFlipper/assets/13990539/e223c609-5988-4246-81dc-ace41d16696c)

注意看全出来那个 比如`些` `很` 几个字, 期望的效果应该是卷起来的感觉, 但是实际效果有点像右侧被压到了一点到左侧上.
我不太确实是算法的问题还是只是计算的精度参数的设置问题...
感谢 @FantasticPornTaiQiang

**Comment by FantasticPornTaiQiang** [comment]
我认为这个是正常现象，你可以用一本现实世界的书，把书页卷起来试试看，在你圈的那个位置，如果从垂直方向往下看，文字的投影对比原来的效果就会像是右侧被压倒了左侧上。

我的翻页组件是仿照ios的翻页组件做的，ios的这个我没猜错的话应该是3d框架实现的，他这个也表现为会有文字挤压。图中我标的黄线的位置，是翻起来的页和底页的接触线（相切线），所以在黄线右侧，都会有卷曲效果，但是当卷曲没那么大时，表现很像是向左挤压。
![image](https://github.com/FantasticPornTaiQiang/PTQFlipper/assets/47035252/b86e09ea-ff23-435d-85af-bdb61f894e65)

关于如何用2d绘制api实现3d的文字扭曲效果，这个算法我录制过视频详细介绍过，你可以看一下是否能解答你的疑惑。

https://www.bilibili.com/video/BV1FP411X7Vu/?spm_id_from=333.337.search-card.all.click&vd_source=b884b778774157b8c60ecc4f3e171cbf

总结一下，就是我个人认为这个向左挤压是个正常现象，现实世界也是这样的。不过你也可以认为是算法的原因，因为毕竟我的翻页器是用2d绘制api模拟3d效果，如果你觉得和你的理想效果有差异，可能我也没法做出改进了。

谢谢你的反馈。

**Comment by FantasticPornTaiQiang** [comment]
这个书籍翻页最好还是用3d框架去实现，那样是最自然的，像我这样以2d模拟3d，多少会有些区别，比如一些阴影和光泽的绘制之类的。感觉2d不太容易做到3d实现的那么真实。

**Comment by Liloupar** [comment]
@FantasticPornTaiQiang 
我也是参考iOS自带的那个翻页效果来说的.
他的相对是个弧度的, 就像一张纸卷起来成桶一样. 但是目前这个demo如果在黄线的位置是有点没卷起来的那种感觉 
emmm
但是还是非常棒的开源翻页库. 感谢

**Comment by Liloupar** [comment]
另外我给flutter官方也提了issue问能不能支持这个. 他们表示暂时没有精力. 
有兴趣可以提个pr. /dog
https://github.com/flutter/flutter/issues/132384

**Comment by FantasticPornTaiQiang** [comment]
哦哦，我又去试了一下我写的这个翻页器。我仔细观察了一下，现在应该是理解你说的，往左挤压是什么意思了。确实如你所说，没有iOS的那么自然。

这两天我抽空思考一下，看看能不能有解决方案稍微去优化一下吧。不过不一定能成功，目前实现的效果已经接近我能做到的极限了。我试试看吧。

另外，我这个compose写的能提flutter的pr吗哈哈哈

**Comment by Liloupar** [comment]
> 哦哦，我又去试了一下我写的这个翻页器。我仔细观察了一下，现在应该是理解你说的，往左挤压是什么意思了。确实如你所说，没有iOS的那么自然。
> 
> 这两天我抽空思考一下，看看能不能有解决方案稍微去优化一下吧。不过不一定能成功，目前实现的效果已经接近我能做到的极限了。我试试看吧。

太感谢了 @FantasticPornTaiQiang 

> 
> 另外，我这个compose写的能提flutter的pr吗哈哈哈

那可能不能, 但是可以基于这个算法复刻一个. :)

**Comment by FantasticPornTaiQiang** [comment]
说实话，现在这个翻页器我自己写完之后已经不想再碰它了（哭）。里面有些代码太绕了（尽管写了很多注释）。flutter版本至少我是没精力去搞了哈哈哈。

**Comment by Liloupar** [comment]
> 说实话，现在这个翻页器我自己写完之后已经不想再碰它了（哭）。里面有些代码太绕了（尽管写了很多注释）。flutter版本至少我是没精力去搞了哈哈哈。

确实, 这东西真是太太太太复杂了

**Comment by Liloupar** [comment]
> 没有iOS的那么自然。
> 
> 这两天我抽空思考一下，看看能不能有解决方案稍微去优化一下吧。不过不一定能成功，目前实现的效果已经接近我能做到的极限了。我试试看吧。

大佬麻烦问下, 这个没有iOS的那么自然的问题, 后面有什么新消息嘛?

**Comment by FantasticPornTaiQiang** [comment]
抱歉，今年一整年有些忙，我的博客更新也停滞了，这个项目暂时没有精力搞，抱歉，有可能的话年底或者明年初再看看
